<?php
/**
 * OrderJsonldOrderReadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\OrderService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Order API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VentureLeap\OrderService;

/**
 * OrderJsonldOrderReadTest Class Doc Comment
 *
 * @category    Class
 * @description OrderJsonldOrderRead
 * @package     VentureLeap\OrderService
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderJsonldOrderReadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderJsonldOrderRead"
     */
    public function testOrderJsonldOrderRead()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "order_code"
     */
    public function testPropertyOrderCode()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "payment_status"
     */
    public function testPropertyPaymentStatus()
    {
    }

    /**
     * Test attribute "payment_date"
     */
    public function testPropertyPaymentDate()
    {
    }

    /**
     * Test attribute "customer_uuid"
     */
    public function testPropertyCustomerUuid()
    {
    }

    /**
     * Test attribute "internal_comment"
     */
    public function testPropertyInternalComment()
    {
    }

    /**
     * Test attribute "customer_comment"
     */
    public function testPropertyCustomerComment()
    {
    }

    /**
     * Test attribute "order_products"
     */
    public function testPropertyOrderProducts()
    {
    }

    /**
     * Test attribute "logs"
     */
    public function testPropertyLogs()
    {
    }

    /**
     * Test attribute "date_of_validity"
     */
    public function testPropertyDateOfValidity()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "order_vouchers"
     */
    public function testPropertyOrderVouchers()
    {
    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {
    }

    /**
     * Test attribute "total_gross_amount"
     */
    public function testPropertyTotalGrossAmount()
    {
    }

    /**
     * Test attribute "total_net_amount"
     */
    public function testPropertyTotalNetAmount()
    {
    }

    /**
     * Test attribute "total_vat_amount"
     */
    public function testPropertyTotalVatAmount()
    {
    }
}
