<?php
/**
 * OrderProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\OrderService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Order API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\OrderService;

use VentureLeap\OrderService\Configuration;
use VentureLeap\OrderService\ApiException;
use VentureLeap\OrderService\ObjectSerializer;

/**
 * OrderProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\OrderService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteOrderProductItem
     *
     * Removes the OrderProduct resource..
     *
     */
    public function testDeleteOrderProductItem()
    {
    }

    /**
     * Test case for getOrderProductCollection
     *
     * Retrieves the collection of OrderProduct resources..
     *
     */
    public function testGetOrderProductCollection()
    {
    }

    /**
     * Test case for getOrderProductItem
     *
     * Retrieves a OrderProduct resource..
     *
     */
    public function testGetOrderProductItem()
    {
    }

    /**
     * Test case for postOrderProductCollection
     *
     * Creates a OrderProduct resource..
     *
     */
    public function testPostOrderProductCollection()
    {
    }

    /**
     * Test case for putOrderProductItem
     *
     * Replaces the OrderProduct resource..
     *
     */
    public function testPutOrderProductItem()
    {
    }
}
